In [2]:
import torch
import torch.nn as nn
from torch.nn import functional as F
import numpy as np
import time # To measure diff between gpu and cpu
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cuda


In [3]:
randint = torch.randint(-100, 100, (6,))
randint # Get Tensor type

tensor([ 74,  79,   8,  86,  60, -66])

In [4]:
tensor = torch.tensor([[0.1, 1.2], [2.2, 3.1], [4.9, 5.2]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [5]:
zeros = torch.zeros(2, 3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [7]:
input = torch.empty(2, 3)
input 

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [9]:
linspace = torch.linspace(3, 10, steps=5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [10]:
logspace = torch.logspace(start=10, end=10, steps = 5)
logspace

tensor([1.0000e+10, 1.0000e+10, 1.0000e+10, 1.0000e+10, 1.0000e+10])

In [11]:
eye = torch.eye(5)
eye # Identity matrix

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [12]:
a = torch.empty((2, 3), dtype=torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[0, 0, 0],
        [0, 0, 0]])

In [13]:
%%time
start_time = time.time()
# matrix operations here
zeros = torch.zeros(1, 1)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

0.00000000
CPU times: total: 0 ns
Wall time: 1 ms


In [14]:
torch_rand1 = torch.rand(100, 100, 100, 100).to(device) # Torch on GPU
torch_rand2 = torch.rand(100, 100, 100, 100).to(device) 
np_rand1 = torch.rand(100, 100, 100, 100) # Numpy on CPU
np_rand2 = torch.rand(100, 100, 100, 100)

start_time = time.time()

rand = (torch_rand1 @ torch_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")


start_time = time.time()

rand = np.multiply(np_rand1, np_rand2)
end_time = time.time()
elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

2.02068710
0.24699545


In [15]:
# embeddings, torch.stack, torch.multinomial, torch.tril, torch.triu, input.T / input.transpose, nn.Linear, torch.cat, F.softmax (show all the examples of functions/methods with pytorch docs)


# Define a probability tensor
probabilities = torch.tensor([0.1, 0.9])
# 10% or 0.1 => 0, 90% or 0.9 => 1. each probability points to the index of the probability in the tensor
# Draw 5 samples from the multinomial distribution
samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
print(samples)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])


In [16]:
tensor = torch.tensor([1, 2, 3, 4])
out = torch.cat((tensor, torch.tensor([5])), dim=0)
out

tensor([1, 2, 3, 4, 5])

In [17]:
out = torch.tril(torch.ones(5, 5)) # Triangle Lower
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [18]:
out = torch.triu(torch.ones(5, 5)) # Triangle Upper
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [19]:
out = torch.zeros(5, 5).masked_fill(torch.tril(torch.ones(5, 5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [20]:
torch.exp(out) # IMP - Exponentiate Converts -inf to 0 and 0 to 1, 2.71^0 & 2.71^-inf

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [21]:
input = torch.zeros(2, 3, 4)
out1 = input.transpose(0, 2) # Flip/Swap the dimentions of tensor, swap 0th (1st) position with 2nd (3rd)
out2 = input.transpose(-2,-1)
print(out1.shape)
print(out2.shape)
# torch.permute works the same but you provide the new order of dimensions instead of the dimensions you'd like 

torch.Size([4, 3, 2])
torch.Size([2, 4, 3])


In [22]:
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])
tensor3 = torch.tensor([7, 8, 9])

# Stack the tensors along a new dimension
stacked_tensor = torch.stack([tensor1, tensor2, tensor3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [24]:
import torch.nn as nn
sample = torch.tensor([10.,10.,10.])
linear = nn.Linear(3, 3, bias=False) # Linear Transformation https://pytorch.org/docs/stable/nn.html
print(linear(sample))

tensor([-4.1585,  2.1912,  6.5493], grad_fn=<SqueezeBackward4>)


In [25]:
import torch.nn.functional as F

# Create a tensor
tensor1 = torch.tensor([1.0, 2.0, 3.0])

# Apply softmax using torch.nn.functional.softmax()
softmax_output = F.softmax(tensor1, dim=0) # Exponentiate and divide by sum of all ex. (1).exp = 2.71^1, 2.71^2...
# [2.71, 7.34. 19.9] = sum = 29.95
# 2.71/29.95 = 0.0900, 0.2447.....
print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [29]:
# Initialize an embedding layer
# nn.Embedding in PyTorch is a layer that converts integer-encoded inputs (such as word indices) into dense vectors,
# allowing a neural network to learn meaningful representations of categorical data.
vocab_size = 80
embedding_dim = 6 # How many elements in a row for one charc
embedding = nn.Embedding(vocab_size, embedding_dim)

# Create some input indices
input_indices = torch.LongTensor([1, 5, 3, 2])

# Apply the embedding layer
embedded_output = embedding(input_indices)

# The output will be a tensor of shape (4, 100), where 4 is the number of inputs
# and 100 is the dimensionality of the embedding vectors
print(embedded_output.shape)
print(embedded_output)

torch.Size([4, 6])
tensor([[ 1.8025,  0.8481, -0.7038,  0.5966, -0.9553,  1.2537],
        [-2.1211, -0.1250, -0.2323,  0.6489, -0.7861,  2.1603],
        [-0.7912, -1.1260,  0.6945,  0.5202,  0.7769, -0.5336],
        [-0.7293, -1.1969,  1.3744, -1.3852, -1.4700,  1.1504]],
       grad_fn=<EmbeddingBackward0>)


In [30]:
a = torch.tensor([[1,2],[3,4],[5,6]])
b = torch.tensor([[7,8,9],[10,11,12]])
# print(a @ b)
print(torch.matmul(a, b))

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
